### ISSUE TITLE
error: mismatch in operand sizes

### ISSUE THREAD

**Issue by certik** [NieDzejkob/2klinux#1]
I tried this in Ubuntu 18.04 with `nasm`:
```
$ ./build.sh 
Assembling stage0... stage0.s:242: error: mismatch in operand sizes
stage0.s:256: error: mismatch in operand sizes
stage0.s:359: error: mismatch in operand sizes
```
The following patch fixes it:
```diff
diff --git a/stage0.s b/stage0.s
index 80a7ac7..5e0be4a 100644
--- a/stage0.s
+++ b/stage0.s
@@ -239,7 +239,7 @@ FindFile:
        cmp al, byte[di]
        jne short .nomatch
        inc di
-       loop short .cmploop
+       loop .cmploop
        popa
 
 ; We have a match! Set LENGTH and load the first cluster.
@@ -253,7 +253,7 @@ FindFile:
        popa
 .next:
        add si, DirEntrySize
-       loop short .loop
+       loop .loop
 ; Load next cluster of the directory and start from the beginning
        push di
        call near ReadNextCluster
@@ -356,7 +356,7 @@ PrintText:
 PrintTextLength:
        lodsb
        call near PrintChar
-       loop short PrintTextLength
+       loop PrintTextLength
        ret
 
 StageZeroFilename:
```

**Comment by meithecatte** [comment]
On Tue, Apr 07, 2020 at 05:29:30PM +0000, Ondřej Čertík wrote:
> I tried this in Ubuntu 18.04 with `nasm`:

Thanks for the heads up! I can reproduce this on my side too. It looks
like I lost the compatibility with nasm after testing with only yasm for
a while. I'd rather keep the explicit jump lengths, so I'll probably
remove nasm from the instructions... "soon".

BTW, from what I can remember when I last touched this codebase, it
might not be entirely working at master. You might want to try some
older commits... (also note the TODO status).

**Comment by certik** [comment]
The `short .loop` ensures that the `.loop` label is within -128 to +127 range, doesn't it? Why would `nasm` complain about "mismatch in operand sizes"?

**Comment by meithecatte** [comment]
It's a mystery, to me, why this happens. nasm can be weird at times. I have determined that the `short`s are safe to remove here, though, as it's the only jump length that's supported by `loop` on x86.

**Comment by certik** [comment]
@NieDzejkob I have two more questions: Is yasm better maintained than nasm? It seems it started as a rewrite, but when comparing the recent commits, it seems nasm is more active:

https://github.com/yasm/yasm/graphs/contributors
https://github.com/certik/nasm/graphs/contributors  (my own copy, since nasm doesn't seem to be officially at github)

My other question is: why would you care how the assembler encodes jumps, whether `short` or `near`? It seems to me it would only affect the final machine code that one instruction is a bit longer than another. Or is there some downside? I am relatively new to assembler, so I just want to understand that.

**Comment by meithecatte** [comment]
On Wed, Apr 08, 2020 at 12:04:37PM -0700, Ondřej Čertík wrote:
> @NieDzejkob I have two more questions: Is yasm better maintained than nasm? It seems it started as a rewrite, but when comparing the recent commits, it seems nasm is more active:
> 
> https://github.com/yasm/yasm/graphs/contributors
> https://github.com/certik/nasm/graphs/contributors  (my own copy, since nasm doesn't seem to be officially at github)
> 
> My other question is: why would you care how the assembler encodes jumps, whether `short` or `near`? It seems to me it would only affect the final machine code that one instruction is a bit longer than another. Or is there some downside? I am relatively new to assembler, so I just want to understand that.

The issue is that I'm quite space-constrained in stage0 and if a jump
requires the longer range, I want to know about it so that I can try to
rearrange the code such that it doesn't anymore ;)

If given a choice, I would probably choose yasm over nasm, but I don't
recall what made me form this preference.

Hope that helps :D

**Comment by certik** [comment]
I see, that makes sense, thanks for the explanation!
